export enum DonacionType {
  DONACION_GET_LIST_REQUEST = 'donacion/DONACION_GET_LIST_REQUEST',
  DONACION_GET_LIST_SUCCESS = 'donacion/DONACION_GET_LIST_SUCCESS',
  DONACION_GET_LIST_FAILURE = 'donacion/DONACION_GET_LIST_FAILURE',
};
